server.port: 9090
spring:
  application:
    name: pedido-service


ribbon:
  eureka:
    enabled: false

entregaService:
  ribbon:
    listOfServers: 0.0.0.0:9292
    ServerListRefreshInterval: 15000